import { cn } from "@/lib/cn";

type SyntheticBadgeProps = {
  /** When false, renders nothing — only synthetic artifacts get marked. */
  synthetic: boolean;
  className?: string;
};

/**
 * Honest labeling for simulated data (master plan §0.1.14): every
 * demo/fulfillment/synthetic artifact must carry a visible SYNTHETIC chip.
 * Renders nothing when the artifact is real.
 */
export default function SyntheticBadge({ synthetic, className }: SyntheticBadgeProps) {
  if (!synthetic) return null;
  return (
    <span
      title="This event was generated by the demo simulation, not by a real integration."
      className={cn(
        "inline-flex items-center rounded-sm border border-warning/50 bg-warning/[0.1] px-1.5 py-[2px]",
        "font-mono text-[0.5625rem] uppercase tracking-[0.14em] leading-none text-warning",
        className
      )}
    >
      Synthetic
    </span>
  );
}
